### ISSUE TITLE
Temat projektu

### ISSUE THREAD

**Issue by gladki24** [gladki24/BountyHunter#1]
To jaki robimy ten projekt?

**Comment by devmichalek** [comment]
Aplikacja pt. "W drodze do pracy"
Aplikacja, w której zaznaczamy skąd wyjeżdzamy i dokąd dojeżdzamy do pracy (zakładamy, że nasza trasa się powtarza).
Na mapie zaznaczamy również miejsca, w których moglibyśmy ewentualnie zrobić postój.
Pomysł polega na tym, że inne osoby również zaznaczają wspomniane miejsca. Aplikacja daje znać użytkownikowi gdy znaleziono inną osoba, która porusza sie ta samą trasą w innym przypadku osoby te się nie "widzą".
Cel to redukcja samochodów na drodzę, redukcja pustych miejsc w aucie, redukcja korków, redukcja kosztów paliwa itd.
Możliwe ustawienia dla użytkownika:
Trasa
Ilość wolnych miejsc w aucie
Cena za dowóz do konkretnych postojów
Godzina wyjazdów z domu/powrotów do domu
Numer telefonu
% pokrywalności trasy
Ważny punkt to: Mozliwosc dodania znajomego tylko wtedy gdy podróżuje tą samą trasą, w przeciwnym wypadku osoba nie jest widoczna i dane są ukryte.
Osoba A ------------
Osoba B **----------
W tym przypadku osoba A może zaproponować osobie B ze podwiezie ją do pracy.
Osoba A -------------
Osoba B ******-----------
Osoba B może zaproponować osobie A ze podjedzie, nastepnie wraz z osobą A przejedzie reszte trasy.
Różnica miedzy blablacar jest taka że nasza trasa jest powtarzalna oraz, że my nie widzimy osoby dopóki nasza trasa sie w jakimś % się nie pokrywa.


Aplikacja pt. "Stolik" - Ktoś otwierający nową restaurację chce udostępnić to ile tak naprawde jest miejsc wolnych w restauracji. Osoba w restauracji zaznacza na mapie pokoi, które stoliki są zajęte, ile aktualnie znajduje się osob w lokalu, ile trzeba mniej więcej czekać na wolne miejsca itd., osoba po drugiej stronie na żywo widzi jak dużo ludzi znajduje się w lokalu + w przypadku gdy zamierza się do niego wybrać planuje swoje przybycie (co również widzą inni użytkownicy).


Aplikacja pt. "Psi Opiekun" - prosta aplikacja do wystawiania usług. Jako właściciel psa jesteśmy w stanie zgłosić, że szukamy kogoś do np. wyprowadzania psów, lub jako pracownik, że szukamy danej pracy.
Cena
Dostępność - gdy jesteśmy pracownikiem
Zdjęcie psa
Imię psa
Kontakt + adres - imię nazwisko nr. telefonu, miejscowość itd.
Opis usługi: np. wyprowadzanie psa, zabawa z psem, tresowanie


Aplikacja pt. "5 sekund" - implementacja gry planszowej 5 sekund


Aplikacja pt. "Twój ogrodnik" - aplikacja, w której wystawiamy oferty pracy w ogródku lub wystawiamy siebie jako pracownika.
Cena
Czas na wykonanie zadania
Data wykonania zadania
Zdjęcie ogródka
Kontakt - imię nazwisko nr. telefonu
Adres
Opis zadania
Opcjonalnie:
Kogo szukasz/kim jesteś: Ogrodnik, Projektant zieleni, Konserwator, Pracownik fizyczny, Pomocnik, Rolnik
Jak daleko jesteś w stanie podjechać (zasięg np. 50km)

**Comment by gladki24** [comment]
@devmichalek Bardzo mi się podoba projekt "Psi opiekun", można się inspirować portalem OLX w wielu rozwiązanich

**Comment by krzysiekaw18** [comment]
Jeśli chodzi o mnie to miałbym 2 pomysły:
1. Aplikacja łącząca lekarzy z pacjentami, tzn jedna aplikacja i możliwość zalogowania się jako lekarz lub pacjent. Jeśli zalogowana osobą jest lekarz to ma dostęp do wszystkich swoich pacjentów razem z jakimiś wynikami badań i dokumentami, plus swój terminarz i bazę dostępnych leków. Jeśli zalogowany byłby pacjent to wiadomo dostęp do bazy lekarzy podzielonych na specjalizacje, miejsce przyjęć, cena wizyty, kalendarz wolnych terminów, wyniki swoich badań, recepty i spis aptek które maja na stanie przepisane leki.
(można dołożyć jakaś funkcjonalność)
2. Prosto aplikacja do rezerwacji miejsc w kinie z wysyłką E-maila potwierdzającego.

**Comment by gladki24** [comment]
@krzysiekaw18 ten drugi pomysł ma potencjał na wykorzystanie może jakiegoś zewnętrznego API do pobierania informacji o tytułach jakie grają w kinie

**Comment by krzysiekaw18** [comment]
Jestem jak najbardziej za. Z tym kinem to taki luźny pomysł, nie zastanawiałem się jakoś dogłębnie nad dokładną funkcjonalnością.

**Comment by gladki24** [comment]
Dokładną analizę wymagań i ustalanie specyfikacji pewnie określimy gdy wybierzemy temat

**Comment by devmichalek** [comment]
@krzysiekaw18 pewnie ten pierwszy temat Ci Ania wymysliła xD

**Comment by krzysiekaw18** [comment]
Jak powiedziałeś o tym api to jeszcze mi wpadł jeden pomysł :) coś w rodzaju kantoru, albo platformy do tradingu :) można się pobawić w wyświetlanie jakichś wykresów, aktualnych kursów walut itp

**Comment by krzysiekaw18** [comment]
Nie:) chodził mi ten pomysł od dłuższego czasu po głowie , tylko nie miałem się kiedy za to zabrać :)

**Comment by gladki24** [comment]
Pewnie chodzi o to, żeby wykorzystać jak największą ilość wzorców

**Comment by krzysiekaw18** [comment]
Wzorce wrzucisz wszędzie :)

**Comment by krzysiekaw18** [comment]
Singleton, Factory, builder i np fasada wszedzie pasuje

**Comment by gladki24** [comment]
I przy tradingu będziemy mieć eksperta domenowego 😄

**Comment by winiarzb** [comment]
Hehe, mam pomysł/potrzebę ale raczej nie na nasze siły, ostatnio często potrzebuje aplikacji, która na podstawie wybranych scen w filmie (np. na youtubie) potrafiłaby ustalić co to za film, coś w stylu shazama tylko że do filmów. Ktoś się podejmuje ? ;P

**Comment by gladki24** [comment]
@winiarzb to jest genialny pomysł, ale usuń ten komentarz, bo to jest publiczne 😄

**Comment by krzysiekaw18** [comment]
Taaaa:) chciałeś ostatnio kupować złoto wiec mozemy rozszerzyć apka o kursy złota :)

**Comment by krzysiekaw18** [comment]
To juz w jakaś machine learning musielibyśmy isc :) wiec podjęcie sie tego teraz byłoby odważne :)

**Comment by krzysiekaw18** [comment]
Takie rzeczy to za rok :)

**Comment by winiarzb** [comment]
Ale jak ktoś to zrobi to zobaczycie że będzie kasowe :)

**Comment by winiarzb** [comment]
O albo od strony motoryzacyjnej, apka w której zbierasz historie napraw ( kiedy, jaki przebieg) wraz ze zdjęciami faktur(mogą być zanonimizowane). Przy sprzedaży udostępniasz i przekazujesz historie auta żeby kupujący dalej ją kontynuował. Aplikacja wylicza oczywiście najbliższe naprawy typu olej rozrząd ale będzie pozwalała też prowadzić takie repozytorium mechaników, którzy sprawdzili się przy naprawie tego auta (gdzie dobrze zrobili ci klime, gdzie się znają na rzeczy itp.) które też będą przekazywane kupującemu

**Comment by winiarzb** [comment]
"Carbook" :)

**Comment by winiarzb** [comment]
żeby było bardziej facebookowo można rozszerzyć o podgląd np. gdzie naprawiają samochód swoi znajomi

**Comment by gladki24** [comment]
Generalnie trochę czytałem o tej inżynierii oprogramowania i w sumie ciekawe rzeczy tam są. Możemy stworzyć na początek coś prostszego i później w zależności od chęci i czasu rozwijać to w kolejnych iteracjach. Trzeba by tylko się dowiedzieć czy model projektowy jaki dostarczymy można rozszerzać.

**Comment by gladki24** [comment]
Z @winiarzb i @krzysiekaw18 wymyśliliśmy taką aplikację trochę z jajem, ale w sumie cel przedmiotu będzie osiągnięty. Aplikacja realizuje portal ogłoszeń dla łowców głów w uniwersum Gwiezdnych Wojen. Jeżeli nikt nie będzie miał nic przeciwko, to z braku lepszych tematów, będziemy realizować ten.

**Comment by gladki24** [comment]
Jak ktoś będzie miał coś przeciwko poleci reopen.
