### ISSUE TITLE
Dodać materiały do nauki do wiki - Java, Spring Boot, Hiberante

### ISSUE THREAD

**Issue by gladki24** [gladki24/BountyHunter#9]
Dodać materiały do nauki

**Comment by dawiddanel** [comment]
Java (od zera)
https://www.youtube.com/watch?v=Hl-zzrqQoSE&list=PLFE2CE09D83EE3E28&fbclid=IwAR1ZD5mT2T9HA1AY7QrsNlvNGgwKM3zEhEtukGJMYPghTofj11G91cuzVTk
Dalej to dowolny kurs, po prostu trzeba pisać. Masochiści mogą robić zadania ze spoja
https://pl.spoj.com/
Spring:
https://spring.io/guides
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/
https://spring.io/guides/gs/spring-boot/
Hibernate:
https://www.baeldung.com/spring-boot-hibernate
https://bykowski.pl/spring-boot-15-integracja-z-baza-danych/

Wpisujesz w google/youtube cokolwiek z SpringBoot + CRUD i jest mnóstwo

Springowe propertiesy (przydatne w konfiguracji): https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
